add astar
bonsairobo/building-blocks pull request #21
Opened 2021-03-12 20:01 UTC by siler

Performed a simple integration for A*. Followed patterns used by `greedy_path`. Throwing up for comments as I have a couple questions:

1. is the layout alright? i.e. just tossing these in the `pathfinding` module.
2. should I add max_iterations to astar?

2021-03-12 20:17 UTC, bonsairobo commented
Oh I expected you to just call into the `pathfinding` crate. Can we just do that instead of copying the code? I only copied code for `greedy_path` because that algorithm doesn't exist in `pathfinding`.

1. Yea just putting the code in pathfinding.rs is fine.
2. No, I think A* is usually chosen when the user wants an optimal path, so I think it should just run to completion.

2021-03-12 20:37 UTC, bonsairobo commented
So it should look really similar to `greedy_path`, but you're calling into `astar` instead of `greedy_best_first`.

2021-03-12 20:45 UTC, bonsairobo requested changes
I'd prefer if we just called into the `pathfinding` crate.

2021-03-12 22:31 UTC, siler commented
Yes this makes a lot more sense. Would you like a feature flag for depending on `pathfinding`?

2021-03-13 00:16 UTC, bonsairobo commented
> Would you like a feature flag for depending on `pathfinding`?

No it's fine to just require it. I don't think it's a big dependency.

2021-03-13 00:19 UTC, bonsairobo approved these changes
awesome!

2021-03-13 00:19 UTC, merged